name: Expo EAS Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  eas-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup EAS CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci || npm i

      - name: Build Android (APK via 'preview' profile)
        run: eas build -p android --profile preview --non-interactive

      - name: Show latest build (non-interactive)
        run: eas build:list --limit 1 --non-interactive

      - name: Print latest build page (QR link)
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          eas build:list --limit 1 --json --non-interactive | jq -r '.[0].webUrl'
