name: Expo Build (Node.js CI)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Expo & EAS CLI
        run: |
          npm install -g eas-cli @expo/cli

      - name: Authenticate with Expo (EAS CLI)
        run: |
          npx eas whoami || npx eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Build Android APK
        run: |
          npx eas build -p android --profile preview --non-interactive

      - name: Upload built APK
        uses: actions/upload-artifact@v4
        with:
          name: expo-apk
          path: dist/
